version: '3'
services:

  zookeeper:  # for kafka
    build:
      context: .
    command: zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties
    volumes:
      - ./zookeeper-1-logs:/tmp/zookeeper/


  # TODO: Kafka
  kafka1:
    build:
      context: .
    ports:
      - "9092:9092" # !!! each Kafka broker must have uniqe port, open Firewall
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # !!! PUBLIC_IP comes from file: .env (inter-broker communication goes through docker-hostname:39092)
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${PUBLIC_IP}:9092,INTERNAL://:39092 # !!! check port
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:39092 # !!! check port
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT # no security here
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: -Xmx200m # only if there is no enough memory
      KAFKA_CREATE_TOPICS: test:3:1 # "test" topic created on startup with 5 partitions and no replication
      KAFKA_PORT: 39092 # needed only by initial topic creation (create-topics.sh)
    volumes:
      - ./kafka-1-logs:/opt/kafka/logs/
    depends_on:
      - zookeeper

  kafka2:
    build:
      context: .
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${PUBLIC_IP}:9093,INTERNAL://:39092
      KAFKA_LISTENERS: EXTERNAL://:9093,INTERNAL://:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: -Xmx200m
    volumes:
      - ./kafka-2-logs:/opt/kafka/logs/
    depends_on:
      - zookeeper

  kafka3:
    build:
      context: .
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${PUBLIC_IP}:9094,INTERNAL://:39092
      KAFKA_LISTENERS: EXTERNAL://:9094,INTERNAL://:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: -Xmx200m
    volumes:
      - ./kafka-3-logs:/opt/kafka/logs/
    depends_on:
      - zookeeper

