version: '2'
services:

  zookeeper:
    image: lpds/kafka:2.7.0
    command: zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties

  kafka:
    image: lpds/kafka:2.7.0
    ports:
      - "9093:9093" # !!! each Kafka broker must have uniqe port, open Firewall
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # !!! PUBLIC_IP comes from file: .env; inter-broker communication goes through docker-hostname:39092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${PUBLIC_IP}:9092,INTERNAL://:39092
      KAFKA_LISTENERS: EXTERNAL://:9093,INTERNAL://:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SSL,INTERNAL:PLAINTEXT # SSL on external
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: -Xmx200m # ! only if there is no enough memory
      KAFKA_CREATE_TOPICS: test:1:1 # ! "test" topic created on startup with 1 partition and no replication
      KAFKA_PORT: 39092 # ! needed only by initial topic creation (create-topics.sh)

ssl.keystore.location=/opt/kafka/config/kafka01.keystore.jks
ssl.keystore.password=vertica
ssl.key.password=vertica

ssl.truststore.location=/opt/kafka/config/kafka.truststore.jks
ssl.truststore.password=vertica

ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1 (default)
ssl.client.auth=required | none (default)
security.inter.broker.protocol = SSL | PLAINTEXT (default)


# test: openssl s_client -debug -connect localhost:9093 -tls1

# kafka-console-producer.sh --broker-list localhost:9093 --topic test --producer.config client-ssl.properties
#without client auth
security.protocol = SSL
ssl.truststore.location = /var/private/ssl/kafka.client.truststore.jks
ssl.truststore.password = test1234

#with client auth
ssl.keystore.location = /var/private/ssl/kafka.client.keystore.jks
ssl.keystore.password = test1234
ssl.key.password = test1234